version: '3.6'

services:
 mysql:
  image: mysql:5.6
  container_name: libquality_mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=libquality
    - MYSQL_USER=user
    - MYSQL_PASSWORD=secret
  ports:
    - "33061:3306"
  volumes:
    - ./database/libquality_test.sql:/docker-entrypoint-initdb.d/libquality_test.sql
  command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
